name: CI

on: [push]

jobs:

build:

runs-on: windows-latest

steps:

- name: Quiero que me muestre la hora
run: date

name: CI

on: [push]
jobs:
build:
runs-on: windows-latest

steps:
- name: Ver la hora
run: date